# -*- coding: utf-8 -*-
"""Project Task Week 5_Kelompok 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3mMPgBP9-swaQ_seZX_zws9IdGPusw0

# **PROJECT TASK WEEK 5**

## **Kelompok 13**
1.   Shofia Nabila
2.   M Bintang Hikmattulloh


---
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

df = pd.read_csv('/Student_Performance.csv')

if df['Extracurricular Activities'].dtype == object:
    df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

ACCENT  = '#1A6FBF'
DANGER  = '#D62728'
MUTED   = '#B0C4DE'
NEUTRAL = '#7F7F7F'
BG      = '#FAFAFA'
TEXT    = '#1C1C1C'
ANNOT   = '#555555'

plt.rcdefaults()

fig, ax = plt.subplots(figsize=(9, 5))
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)

corr_pi = df.corr()['Performance Index'].drop('Performance Index').sort_values()

colors_bar = [
    DANGER if abs(v) >= 0.7 else
    MUTED
    for v in corr_pi
]

bars = ax.barh(corr_pi.index, corr_pi.values, color=colors_bar,
               height=0.55, edgecolor='white', linewidth=0.6)

for bar, val in zip(bars, corr_pi.values):
    offset = 0.01 if val >= 0 else -0.01
    ha     = 'left' if val >= 0 else 'right'
    ax.text(val + offset, bar.get_y() + bar.get_height() / 2,
            f'{val:.2f}', va='center', ha=ha,
            fontsize=10, color=TEXT)

ax.axvline(0, color=NEUTRAL, linewidth=0.8, linestyle='--')
ax.set_xlim(0.0, 1.0)
ax.set_xlabel('Nilai Korelasi terhadap Performance Index', fontsize=10, color=TEXT)
ax.spines[['top', 'right', 'left', 'bottom']].set_visible(True)
ax.tick_params(left=True, bottom=True, labelsize=9)

# Add annotation for Previous Scores
prev_scores_idx = corr_pi.index.get_loc('Previous Scores')
prev_scores_bar = bars[prev_scores_idx]
ax.annotate(
    'Sangat Dominan',
    xy=(prev_scores_bar.get_width() / 2, prev_scores_bar.get_y() - 0.1), # Position text below and centered on the bar
    fontsize=9, color=ANNOT, ha='center', va='top'
)

ax.set_title(
    'Previous Score Mendominasi Performance Index (r=0.92)',
    fontsize=12, fontweight='bold', color=TEXT, pad=14, loc='center'
)

plt.tight_layout(rect=[0, 0.08, 1, 1])
plt.show()

fig, ax = plt.subplots(figsize=(9, 5.5))
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)

low_mask  = df['Previous Scores'] < 70
high_mask = df['Previous Scores'] >= 70

sample_low  = df[low_mask].sample(700, random_state=42)
sample_high = df[high_mask].sample(700, random_state=42)

ax.scatter(sample_low['Previous Scores'],  sample_low['Performance Index'],
           alpha=0.1, s=8, color=DANGER)
ax.scatter(sample_high['Previous Scores'], sample_high['Performance Index'],
           alpha=0.1, s=8, color=MUTED)

m, b   = np.polyfit(df['Previous Scores'], df['Performance Index'], 1)
x_line = np.linspace(df['Previous Scores'].min(), df['Previous Scores'].max(), 200)
r_val  = df['Previous Scores'].corr(df['Performance Index'])
ax.plot(x_line, m * x_line + b, color=DANGER, linewidth=2.2,
        label=f'Garis Tren  (r = {r_val:.2f})', zorder=5)

ax.axvspan(df['Previous Scores'].min(), 70, alpha=0.2, color=DANGER) # Increased alpha for emphasis
ax.axvline(70, color=TEXT, linewidth=1, linestyle='--')

# Modified text to clarify threshold and zones
ax.text(69, ax.get_ylim()[0] + 2, # Position slightly left of 70 for centering
        'Butuh Intervensi (<70) <-- Threshold (70) --> Stabil (>70)',
        fontsize=9, color=TEXT, va='bottom', ha='center')

ax.set_xlabel('Previous Scores (Nilai Sebelumnya)', fontsize=10, color=TEXT)
ax.set_ylabel('Performance Index', fontsize=10, color=TEXT)
ax.spines[['top', 'right']].set_visible(True)
ax.tick_params(left=True, bottom=True, labelsize=9)

# Add legend to distinguish scatter points
ax.legend(fontsize=9, frameon=False, loc='upper left')

ax.set_title(
    'Siswa dengan Nilai Awal Rendah Cenderung Tetap Tertinggal\n'
    'dan Membutuhkan Intervensi',
    fontsize=12, fontweight='bold', color=TEXT, pad=12, loc='center'
)

plt.tight_layout(rect=[0, 0.08, 1, 1])
plt.show()

fig, ax = plt.subplots(figsize=(9, 5.5))
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)

df2 = df.copy()
df2['Hours_Bin'] = df2['Hours Studied'].round().astype(int).clip(1, 9)

groups  = [df2[df2['Hours_Bin'] == h]['Performance Index'].values for h in range(1, 10)]
medians = [np.median(g) for g in groups]

bp = ax.boxplot(
    groups,
    positions    = range(1, 10),
    widths       = 0.55,
    patch_artist = True,
    medianprops  = dict(color=DANGER,  linewidth=2.5),
    whiskerprops = dict(color=NEUTRAL, linewidth=1.0),
    capprops     = dict(color=NEUTRAL, linewidth=1.0),
    flierprops   = dict(marker='.', alpha=0.12, color='#cccccc', markersize=3),
    boxprops     = dict(linewidth=0.8)
)

for i, patch in enumerate(bp['boxes']):
    patch.set_facecolor('#F0F0F0') # All boxes soft gray
    patch.set_edgecolor('#aaaaaa')

for i, median in enumerate(medians):
    ax.text(i + 1, median + 1.8, f'{median:.0f}',
            ha='center', va='bottom', fontsize=9,
            fontweight='bold', color=TEXT)

# Add median trend line
ax.plot(range(1, 10), medians, color=NEUTRAL, linestyle='-', linewidth=1.5, marker='o', markersize=4, zorder=3, label='Median Trend')

# Add shading for 6-8 hours
ax.axvspan(5.5, 8.5, alpha=0.15, color=ACCENT, zorder=0)

ax.set_xticks(range(1, 10))
ax.set_xticklabels([f'{h} Jam' for h in range(1, 10)], fontsize=9)
ax.set_xlabel('Jam Belajar/Hari', fontsize=10, color=TEXT)
ax.set_ylabel('Performance Index', fontsize=10, color=TEXT)
ax.spines[['top', 'right', 'left', 'bottom']].set_visible(True) # Restore spines for consistency
ax.tick_params(left=True, bottom=True, labelsize=9)

# Main annotation
ax.annotate(
    '''Kualitas belajar lebih penting dari kuantitas.
Optimal: 6-8 jam/hari.''',
    xy=(7, medians[6]),
    xytext=(7.5, ax.get_ylim()[0] + 5), # Adjust y-position to be near the bottom
    fontsize=9, color=ANNOT, ha='center', va='bottom', # va='top' might be better depending on desired exact placement
    bbox=dict(boxstyle='round,pad=0.5', fc=BG, ec=ANNOT, lw=0.8, alpha=0.9)
)

ax.set_title(
    'Efektivitas Belajar Mencapai Titik Optimal di 6–8 Jam Belajar/Hari',
    fontsize=12, fontweight='bold', color=TEXT, pad=12, loc='center'
)


plt.tight_layout(rect=[0, 0.08, 1, 1])

plt.show()

